# Generated by Django 2.0.2 on 2018-02-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='description',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='name',
            field=models.CharField(default='hello', max_length=255),
            preserve_default=False,
        ),
    ]
