# Generated by Django 2.0.2 on 2018-02-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_auto_20180211_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='last_updated',
            field=models.DateField(null=True),
        ),
    ]
